INSERT INTO TB_CONTA(DESCRICAO, VALOR) VALUES ('ENERGIA', 450);
INSERT INTO TB_CONTA(DESCRICAO, VALOR) VALUES ('AGUA', 100);
INSERT INTO TB_CONTA(DESCRICAO, VALOR) VALUES ('INTERNET', 100);

INSERT INTO TB_PERFIL(ID, DESCRICAO) VALUES (1, 'ROLE_ADMIN');
INSERT INTO TB_PERFIL(ID, DESCRICAO) VALUES (2, 'ROLE_USER');

INSERT INTO TB_ACESSO(ID, DESCRICAO, PERFIL_ID) VALUES (1, 'CONTA', 1)
INSERT INTO TB_ACESSO(ID, DESCRICAO, PERFIL_ID) VALUES (2, 'HOME', 1)
INSERT INTO TB_ACESSO(ID, DESCRICAO, PERFIL_ID) VALUES (3, 'PAGE1', 1)
INSERT INTO TB_ACESSO(ID, DESCRICAO, PERFIL_ID) VALUES (4, 'PAGE2', 2)
INSERT INTO TB_ACESSO(ID, DESCRICAO, PERFIL_ID) VALUES (5, 'PAGE3', 1)

INSERT INTO TB_USUARIO(ID, NOME, SENHA, PERFIL_ID) VALUES (1, 'VINICIUS', '$2a$12$AqfpPrBKpXRPsASh5w6FE.raFn9QJl1TlcPFokuAzTyN2aS88zE3q', 1);
INSERT INTO TB_USUARIO(ID, NOME, SENHA, PERFIL_ID) VALUES (2, 'MATHEUS', '$2a$12$AqfpPrBKpXRPsASh5w6FE.raFn9QJl1TlcPFokuAzTyN2aS88zE3q', 2);

SELECT * FROM TB_USUARIO;